### ISSUE TITLE
White line?

### ISSUE THREAD

**Issue by GingkathFox** [lufinkey/iSSB#6] opened 2018-02-17 14:13 UTC
![b159a65f-62c6-4c95-a2e3-c0e4a0a7f6ba](https://user-images.githubusercontent.com/33764485/36341858-a9851272-13c2-11e8-9393-e6869a3c031f.png)
There’s this strange white line on the side of my screen, maybe the black bars aren’t properly resized?

**Comment by lufinkey** [comment] 2018-02-17 15:40
Duplicate of #1

**Closed by lufinkey** 2018-02-17 15:40 UTC
